### ISSUE TITLE
Not able to compile code

### ISSUE THREAD

**Issue by bytesByHarsh** [yuanhui360/CPP-Programming-on-Linux#1]
Hi

So I tried compiling the code present at [YH-123](https://github.com/yuanhui360/CPP-Programming-on-Linux/tree/main/YH-123)

The first error was because of the use of spaces instead of tabs, which I resolved by changing the makefile indentation.

After that when I run `make all` it is giving following error message:

```bash
g++ -lcrypto -lssl -lrt -lpthread -lboost_system generate_x509.o x509_certificate.o -o generate_x509
/usr/bin/ld: x509_certificate.o: in function `LibOpenSSL::My_X509_Certificate::generate_rsa_key(unsigned int)':
YH-123/x509_certificate.cpp:20: undefined reference to `EVP_PKEY_new'
/usr/bin/ld: YH-123/x509_certificate.cpp:28: undefined reference to `EVP_PKEY_CTX_new_id'
/usr/bin/ld: YH-123/x509_certificate.cpp:36: undefined reference to `EVP_PKEY_keygen_init'
...
```

Can you help me resolve this issue?

**Comment by yuanhui360** [comment]
Good Morning Hash
Thanks for watching and try this example, are you using Ubutun Linux ?
For Ubutun Linux, you need to place all used library and .o file before the main() obj file in Makefile.
In this example, place x509_certificate.o before the generate_x509.o.
g++ -lcrypto -lssl -lrt -lpthread -lboost_system x509_certificate.o  generate_x509.o -o generate_x509

Below is the link on my YouTube channel explained this issue for Ubutun Linux.
https://youtu.be/lTYqvBKImak

**Comment by yuanhui360** [comment]
Good Morning HashThanks for watching and try this example, are you using Ubutun Linux ?For Ubutun Linux, you need to place all used library and .o file before the main() obj file in Makefile.In this example, try to place x509_certificate.o before the generate_x509.o.in Makefileg++ -lcrypto -lssl -lrt -lpthread -lboost_system x509_certificate.o  generate_x509.o -o generate_x509
Below is the link on my YouTube channel explained this issue for Ubutun Linux.https://youtu.be/lTYqvBKImak

    On Tuesday, August 16, 2022 at 06:32:21 a.m. EDT, Harsh Mittal ***@***.***> wrote:  
 
 


Hi

So I tried compiling the code present at YH-123

The first error was because of the use of spaces instead of tabs, which I resolved by changing the makefile indentation.

After that when I run make all it is giving following error message:
g++ -lcrypto -lssl -lrt -lpthread -lboost_system generate_x509.o x509_certificate.o -o generate_x509
/usr/bin/ld: x509_certificate.o: in function `LibOpenSSL::My_X509_Certificate::generate_rsa_key(unsigned int)':
YH-123/x509_certificate.cpp:20: undefined reference to `EVP_PKEY_new'
/usr/bin/ld: YH-123/x509_certificate.cpp:28: undefined reference to `EVP_PKEY_CTX_new_id'
/usr/bin/ld: YH-123/x509_certificate.cpp:36: undefined reference to `EVP_PKEY_keygen_init'
...
Can you help me resolve this issue?

**Comment by bytesByHarsh** [comment]
Hi, 
Thanks for replying back.

Yes I am using Ubuntu 20

I have modified the makefile like :
```make
CC=g++
CFLAGS= -c -Wall -g
# LDFLAGS = -lcrypto -lssl -lrt -lpthread -lboost_system -L/usr/local/ssl/lib -I/usr/local/ssl/include

LDFLAGS = -L/usr/local/ssl/lib -I/usr/local/ssl/include -lcrypto -lssl -lrt -lpthread -lboost_system

all: generate_x509 verify_x509 display_x509

generate_x509: generate_x509.o x509_certificate.o
	$(CC) $(LDFLAGS) x509_certificate.o generate_x509.o -o generate_x509
generate_x509.o: generate_x509.cpp
	$(CC) $(LDFLAGS) $(CFLAGS) generate_x509.cpp -o generate_x509.o

verify_x509: verify_x509.o x509_certificate.o
	$(CC) $(LDFLAGS) x509_certificate.o verify_x509.o -o verify_x509
verify_x509.o: verify_x509.cpp
	$(CC) $(LDFLAGS) $(CFLAGS) verify_x509.cpp -o verify_x509.o

display_x509: display_x509.o x509_certificate.o
	$(CC) $(LDFLAGS) x509_certificate.o display_x509.o -o display_x509
display_x509.o: display_x509.cpp
	$(CC) $(LDFLAGS) $(CFLAGS) display_x509.cpp -o display_x509.o

x509_certificate.o: x509_certificate.cpp
	$(CC) $(LDFLAGS) $(CFLAGS) x509_certificate.cpp -o x509_certificate.o

clean:
	rm -f *.o generate_x509 verify_x509 display_x509
```

Also, I have installed `openssl` from the source to ensure I have all the necessary lib.

Still, I am getting errors like:
```bash
g++ -L/usr/local/ssl/lib -I/usr/local/ssl/include -lcrypto -lssl -lrt -lpthread -lboost_system -c -Wall -g generate_x509.cpp -o generate_x509.o
g++ -L/usr/local/ssl/lib -I/usr/local/ssl/include -lcrypto -lssl -lrt -lpthread -lboost_system -c -Wall -g x509_certificate.cpp -o x509_certificate.o
g++ -L/usr/local/ssl/lib -I/usr/local/ssl/include -lcrypto -lssl -lrt -lpthread -lboost_system x509_certificate.o generate_x509.o -o generate_x509
/usr/bin/ld: x509_certificate.o: in function `LibOpenSSL::My_X509_Certificate::generate_rsa_key(unsigned int)':

x509_certificate.cpp:20: undefined reference to `EVP_PKEY_new'
x509_certificate.cpp:28: undefined reference to `EVP_PKEY_CTX_new_id'
x509_certificate.cpp:36: undefined reference to `EVP_PKEY_keygen_init'
x509_certificate.cpp:44: undefined reference to `RSA_pkey_ctx_ctrl'
.
.
.
```

**Comment by yuanhui360** [comment]
Hi Hash
These EVP_PKEY_xxxx functions are all from Openssl library, and ld cannot find them. It mostly looks like your Linux setup.I saw you specified -L/usr/local/ssl/lib -I/usr/local/ssl/include in your makefile, please check where the library libcrypto.so location. on my ubutun environment, library located under : /lib/x86_64-linux-gnu/libcrypto.so, /lib/x86_64-linux-gnu/libssl.soheader file located under /usr/include/openssl/*.h
If you have installed header file and library under different directory, #include <> might require to specify path, and ldconfig need udate which ld is able to find the library
1) check if #include line in your program, and see if it is able to find Openssl header file, 2) check if library  location if -L specified correctly, if these library in standard directory, there is no need to specify -L 3) maybe you need to refresh ld catch, check ldconfig setup in your Linux environment.
Wish it helpsHui



    On Tuesday, August 16, 2022 at 09:34:56 a.m. EDT, Harsh Mittal ***@***.***> wrote:  
 
 


I have modified the makefile like :
CC=g++
CFLAGS= -c -Wall -g
# LDFLAGS = -lcrypto -lssl -lrt -lpthread -lboost_system -L/usr/local/ssl/lib -I/usr/local/ssl/include

LDFLAGS = -L/usr/local/ssl/lib -I/usr/local/ssl/include -lcrypto -lssl -lrt -lpthread -lboost_system

all: generate_x509 verify_x509 display_x509

generate_x509: generate_x509.o x509_certificate.o
	$(CC) $(LDFLAGS) x509_certificate.o generate_x509.o -o generate_x509
generate_x509.o: generate_x509.cpp
	$(CC) $(LDFLAGS) $(CFLAGS) generate_x509.cpp -o generate_x509.o

verify_x509: verify_x509.o x509_certificate.o
	$(CC) $(LDFLAGS) x509_certificate.o verify_x509.o -o verify_x509
verify_x509.o: verify_x509.cpp
	$(CC) $(LDFLAGS) $(CFLAGS) verify_x509.cpp -o verify_x509.o

display_x509: display_x509.o x509_certificate.o
	$(CC) $(LDFLAGS) x509_certificate.o display_x509.o -o display_x509
display_x509.o: display_x509.cpp
	$(CC) $(LDFLAGS) $(CFLAGS) display_x509.cpp -o display_x509.o

x509_certificate.o: x509_certificate.cpp
	$(CC) $(LDFLAGS) $(CFLAGS) x509_certificate.cpp -o x509_certificate.o

clean:
	rm -f *.o generate_x509 verify_x509 display_x509
Also, I have installed openssl from the source to ensure I have all the necessary lib.

Still, I am getting errors like:
g++ -L/usr/local/ssl/lib -I/usr/local/ssl/include -lcrypto -lssl -lrt -lpthread -lboost_system -c -Wall -g generate_x509.cpp -o generate_x509.o
g++ -L/usr/local/ssl/lib -I/usr/local/ssl/include -lcrypto -lssl -lrt -lpthread -lboost_system -c -Wall -g x509_certificate.cpp -o x509_certificate.o
g++ -L/usr/local/ssl/lib -I/usr/local/ssl/include -lcrypto -lssl -lrt -lpthread -lboost_system x509_certificate.o generate_x509.o -o generate_x509
/usr/bin/ld: x509_certificate.o: in function `LibOpenSSL::My_X509_Certificate::generate_rsa_key(unsigned int)':

x509_certificate.cpp:20: undefined reference to `EVP_PKEY_new'
x509_certificate.cpp:28: undefined reference to `EVP_PKEY_CTX_new_id'
x509_certificate.cpp:36: undefined reference to `EVP_PKEY_keygen_init'
x509_certificate.cpp:44: undefined reference to `RSA_pkey_ctx_ctrl'
.
.
.

**Comment by bytesByHarsh** [comment]
Hi

I have all my `.so` files in the proper directory. Still, the makefile is not working.

As a workaround, I used the CMake file to generate binaries and that seems to be working for me.

Thank you so much for your help!
